version: "3.1"
volumes:
    node_modules:
services:
    google_search:
        image: nimashoghi/node
        volumes:
            - ..:/workspace
            - node_modules:/workspace/node_modules
            - ~/.gitconfig:/root/.gitconfig
            - /var/run/docker.sock:/var/run/docker.sock
        command: sleep infinity
